# Generated by Django 3.2.14 on 2022-08-10 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight_app', '0002_auto_20220808_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airport',
            options={'verbose_name': 'Airport'},
        ),
    ]
