# Generated by Django 3.2.14 on 2022-08-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_app', '0004_auto_20220820_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_address',
            field=models.JSONField(default={}, verbose_name='address'),
            preserve_default=False,
        ),
    ]
