# Generated by Django 3.2.14 on 2022-08-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_app', '0005_customer_customer_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Phone_No',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_address',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Address',
            field=models.JSONField(default={}, verbose_name='address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Phone_No',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='Credit_Card_No',
            field=models.CharField(max_length=50),
        ),
    ]
