# Generated by Django 3.2.14 on 2022-08-28 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight_app', '0006_auto_20220827_1156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Profile'},
        ),
        migrations.RemoveField(
            model_name='flight',
            name='Destination_Country_Id',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='Origin_Country_Id',
        ),
        migrations.AddField(
            model_name='flight',
            name='Arrival_airport_id',
            field=models.ForeignKey(default=1986, on_delete=django.db.models.deletion.CASCADE, related_name='Destination_airport_Id', to='flight_app.airport'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='Departure_airport_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Origin_airport_Id', to='flight_app.airport'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Address',
            field=models.JSONField(default={'city': '', 'postcode': 0, 'state': '', 'street': ''}, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Phone_No',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
