# Generated by Django 3.2.14 on 2022-08-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_app', '0008_auto_20220829_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flight_range',
            field=models.IntegerField(default=0),
        ),
    ]
