# Generated by Django 3.2.14 on 2022-08-30 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight_app', '0009_alter_flight_flight_range'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='Ticket_Id',
        ),
    ]
