# Generated by Django 3.2.14 on 2022-08-30 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight_app', '0010_remove_ticket_ticket_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
