# Generated by Django 4.1.4 on 2023-02-01 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("esc", "0001_initial"),
        ("geo", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.userprofile"
            ),
        ),
        migrations.AddField(
            model_name="flight",
            name="airline",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="geo.airline_company",
            ),
        ),
        migrations.AddField(
            model_name="flight",
            name="flight_route",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="geo.flattenedflightroutes",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.userprofile"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="esc.customer"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="flight",
            field=models.ManyToManyField(to="esc.flight"),
        ),
    ]
