# Generated by Django 4.1.4 on 2022-12-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esc", "0004_remove_flight_airline_company_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="seats",
            new_name="passengers",
        ),
        migrations.AddField(
            model_name="booking",
            name="created",
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
