# Generated by Django 4.1.4 on 2022-12-28 18:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('esc', '0005_rename_seats_booking_passengers_booking_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='depart_sched',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='flight',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='minutes of flight'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_number',
            field=models.CharField(blank=True, max_length=120, unique=True),
        ),
    ]
