# Generated by Django 4.1.4 on 2023-01-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esc", "0006_alter_flight_depart_sched_alter_flight_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="duration",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="hours",
            ),
        ),
    ]
