# Generated by Django 4.1.4 on 2022-12-25 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airline_Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=2, unique=True, verbose_name="IATA Code"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Airline Name"
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Airline",
            },
        ),
        migrations.CreateModel(
            name="Airport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icao_code", models.CharField(max_length=4, null=True)),
                ("iata_code", models.CharField(max_length=3, null=True)),
                ("display_name", models.CharField(default="", max_length=50)),
                ("name", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("lat_decimal", models.FloatField()),
                ("lon_decimal", models.FloatField()),
            ],
            options={
                "verbose_name": "Airport",
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=2, unique=True, verbose_name="IATA Code"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=20, unique=True, verbose_name="Name"),
                ),
                (
                    "flag",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Flag URL"
                    ),
                ),
            ],
            options={
                "verbose_name": "Country",
            },
        ),
        migrations.CreateModel(
            name="FlightRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ident",
                    models.IntegerField(
                        blank=True, unique=True, verbose_name="Flight route ID"
                    ),
                ),
                ("distance", models.IntegerField(blank=True, default=0)),
                (
                    "airline",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geo.airline_company",
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Destination_Airport",
                        to="geo.airport",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Origin_Airport",
                        to="geo.airport",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FlattenedFlightRoutes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, help_text="from to code", max_length=7, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, help_text="from to literal", max_length=120
                    ),
                ),
                ("distance", models.IntegerField(blank=True, default=0)),
                (
                    "airlines",
                    models.ManyToManyField(blank=True, to="geo.airline_company"),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Destination",
                        to="geo.airport",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Origin",
                        to="geo.airport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Flight routes by airlines",
            },
        ),
        migrations.AddField(
            model_name="airport",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="geo.country"
            ),
        ),
        migrations.AddField(
            model_name="airline_company",
            name="country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="geo.country",
                verbose_name="Base Country",
            ),
        ),
    ]
