# Generated by Django 4.1.4 on 2023-01-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="airport",
            name="country_code",
            field=models.CharField(default="NON", max_length=3, null=True),
        ),
    ]
